### ISSUE TITLE
Commands: Vaccine Availabilities

### ISSUE THREAD

**Issue by alvintangz** [Vaccine-Hunters-Canada/VaxFinder-admin-cli#1]
- [ ] `vf-admin va get <id>`
- [ ] `vf-admin va list`
- [ ] `vf-admin va add`
- [ ] `vf-admin va update <id>`
- [ ] `vf-admin va remove <id>`

The issue includes all of the commands mentioned above. For all of them except the last command, print out the response on a table. Any values from the HTTP body request should be set as a key (check if schema sets it as required or not). The `list` command may utilize `page` and `size` as keys as well but they are not required (page is set to 1 by default and size is set to 12 by default). *Note that pagination may have not been implemented yet in the API.*

Don't forget to document all commands carefully and run `make docs` or `go run ./scripts/gen-docs/main.go` to generate documentation on the commands you created.

Before committing, make sure you have `pre-commit` hooks installed. If not, run `gofmt`, `go lint` and `go vet` by yourself.

💉 💉 💉

**Comment by EricStG** [comment]
The VA return payload is pretty large

```json
{
  "numberAvailable": 0,
  "numberTotal": 0,
  "vaccine": 0,
  "inputType": 1,
  "tags": "string",
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "location": {
    "name": "string",
    "phone": "string",
    "notes": "string",
    "active": 0,
    "postcode": "string",
    "url": "string",
    "tags": "string",
    "externalKey": "string",
    "id": 0,
    "organization": {
      "fullName": "string",
      "shortName": "string",
      "description": "string",
      "url": "string",
      "id": 0,
      "createdAt": "2021-05-21T00:06:23.405Z"
    },
    "address": {
      "line1": "string",
      "line2": "string",
      "city": "string",
      "province": "string",
      "postcode": "string",
      "id": 0,
      "createdAt": "2021-05-21T00:06:23.405Z"
    },
    "createdAt": "2021-05-21T00:06:23.405Z"
  },
  "createdAt": "2021-05-21T00:06:23.405Z",
  "timeslots": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "vaccineAvailability": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "time": "2021-05-21T00:06:23.405Z",
      "takenAt": "2021-05-21T00:06:23.405Z",
      "createdAt": "2021-05-21T00:06:23.405Z"
    }
  ],
  "requirements": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "vaccineAvailability": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "requirement": 0,
      "active": true,
      "name": "string",
      "description": "string",
      "createdAt": "2021-05-21T00:06:23.405Z"
    }
  ],
  "date": "2021-05-21T00:06:23.405Z"
}
```

Do we want to display ALL the fields? If so, how do we want to display arrays (timeslots/requirements)?

**Comment by alvintangz** [comment]
Don't need to display timeslots or requirements. For location you can pass in the id for it, the name, address, province, org full name. That should be good enough
