### ISSUE TITLE
Commands: VA Requirements

### ISSUE THREAD

**Issue by alvintangz** [Vaccine-Hunters-Canada/VaxFinder-admin-cli#4]
- [ ] `vf-admin va requirement list <va-id>`
- [ ] `vf-admin va requirement add <va-id>`
- [ ] `vf-admin va requirement update <va-id> <id>`
- [ ] `vf-admin va requirement remove <va-id> <id>`

The issue includes all of the commands mentioned above. For all of them except the last command, print out the response on a table. Any values from the HTTP body request should be set as a key (check if schema sets it as required or not).

Don't forget to document all commands carefully and run `make docs` or `go run ./scripts/gen-docs/main.go` to generate documentation on the commands you created.

Before committing, make sure you have `pre-commit` hooks installed. If not, run `gofmt`, `go lint` and `go vet` by yourself.

💉 💉 💉

**Comment by EricStG** [comment]
@alvintangz Looks like there is no `get` operation for this. Is that missing from the api or should we just skip it?

**Comment by alvintangz** [comment]
You can skip that. Forgot that there wasn't an API for that sorry
